require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PersonalPlantWateringsController do

  # This should return the minimal set of attributes required to create a valid
  # PersonalPlantWatering. As you add validations to PersonalPlantWatering, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PersonalPlantWateringsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all personal_plant_waterings as @personal_plant_waterings" do
      personal_plant_watering = PersonalPlantWatering.create! valid_attributes
      get :index, {}, valid_session
      assigns(:personal_plant_waterings).should eq([personal_plant_watering])
    end
  end

  describe "GET show" do
    it "assigns the requested personal_plant_watering as @personal_plant_watering" do
      personal_plant_watering = PersonalPlantWatering.create! valid_attributes
      get :show, {:id => personal_plant_watering.to_param}, valid_session
      assigns(:personal_plant_watering).should eq(personal_plant_watering)
    end
  end

  describe "GET new" do
    it "assigns a new personal_plant_watering as @personal_plant_watering" do
      get :new, {}, valid_session
      assigns(:personal_plant_watering).should be_a_new(PersonalPlantWatering)
    end
  end

  describe "GET edit" do
    it "assigns the requested personal_plant_watering as @personal_plant_watering" do
      personal_plant_watering = PersonalPlantWatering.create! valid_attributes
      get :edit, {:id => personal_plant_watering.to_param}, valid_session
      assigns(:personal_plant_watering).should eq(personal_plant_watering)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PersonalPlantWatering" do
        expect {
          post :create, {:personal_plant_watering => valid_attributes}, valid_session
        }.to change(PersonalPlantWatering, :count).by(1)
      end

      it "assigns a newly created personal_plant_watering as @personal_plant_watering" do
        post :create, {:personal_plant_watering => valid_attributes}, valid_session
        assigns(:personal_plant_watering).should be_a(PersonalPlantWatering)
        assigns(:personal_plant_watering).should be_persisted
      end

      it "redirects to the created personal_plant_watering" do
        post :create, {:personal_plant_watering => valid_attributes}, valid_session
        response.should redirect_to(PersonalPlantWatering.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved personal_plant_watering as @personal_plant_watering" do
        # Trigger the behavior that occurs when invalid params are submitted
        PersonalPlantWatering.any_instance.stub(:save).and_return(false)
        post :create, {:personal_plant_watering => {}}, valid_session
        assigns(:personal_plant_watering).should be_a_new(PersonalPlantWatering)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PersonalPlantWatering.any_instance.stub(:save).and_return(false)
        post :create, {:personal_plant_watering => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested personal_plant_watering" do
        personal_plant_watering = PersonalPlantWatering.create! valid_attributes
        # Assuming there are no other personal_plant_waterings in the database, this
        # specifies that the PersonalPlantWatering created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PersonalPlantWatering.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => personal_plant_watering.to_param, :personal_plant_watering => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested personal_plant_watering as @personal_plant_watering" do
        personal_plant_watering = PersonalPlantWatering.create! valid_attributes
        put :update, {:id => personal_plant_watering.to_param, :personal_plant_watering => valid_attributes}, valid_session
        assigns(:personal_plant_watering).should eq(personal_plant_watering)
      end

      it "redirects to the personal_plant_watering" do
        personal_plant_watering = PersonalPlantWatering.create! valid_attributes
        put :update, {:id => personal_plant_watering.to_param, :personal_plant_watering => valid_attributes}, valid_session
        response.should redirect_to(personal_plant_watering)
      end
    end

    describe "with invalid params" do
      it "assigns the personal_plant_watering as @personal_plant_watering" do
        personal_plant_watering = PersonalPlantWatering.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PersonalPlantWatering.any_instance.stub(:save).and_return(false)
        put :update, {:id => personal_plant_watering.to_param, :personal_plant_watering => {}}, valid_session
        assigns(:personal_plant_watering).should eq(personal_plant_watering)
      end

      it "re-renders the 'edit' template" do
        personal_plant_watering = PersonalPlantWatering.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PersonalPlantWatering.any_instance.stub(:save).and_return(false)
        put :update, {:id => personal_plant_watering.to_param, :personal_plant_watering => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested personal_plant_watering" do
      personal_plant_watering = PersonalPlantWatering.create! valid_attributes
      expect {
        delete :destroy, {:id => personal_plant_watering.to_param}, valid_session
      }.to change(PersonalPlantWatering, :count).by(-1)
    end

    it "redirects to the personal_plant_waterings list" do
      personal_plant_watering = PersonalPlantWatering.create! valid_attributes
      delete :destroy, {:id => personal_plant_watering.to_param}, valid_session
      response.should redirect_to(personal_plant_waterings_url)
    end
  end

end
