require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PersonalPlantsController do

  # This should return the minimal set of attributes required to create a valid
  # PersonalPlant. As you add validations to PersonalPlant, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PersonalPlantsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all personal_plants as @personal_plants" do
      personal_plant = PersonalPlant.create! valid_attributes
      get :index, {}, valid_session
      assigns(:personal_plants).should eq([personal_plant])
    end
  end

  describe "GET show" do
    it "assigns the requested personal_plant as @personal_plant" do
      personal_plant = PersonalPlant.create! valid_attributes
      get :show, {:id => personal_plant.to_param}, valid_session
      assigns(:personal_plant).should eq(personal_plant)
    end
  end

  describe "GET new" do
    it "assigns a new personal_plant as @personal_plant" do
      get :new, {}, valid_session
      assigns(:personal_plant).should be_a_new(PersonalPlant)
    end
  end

  describe "GET edit" do
    it "assigns the requested personal_plant as @personal_plant" do
      personal_plant = PersonalPlant.create! valid_attributes
      get :edit, {:id => personal_plant.to_param}, valid_session
      assigns(:personal_plant).should eq(personal_plant)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PersonalPlant" do
        expect {
          post :create, {:personal_plant => valid_attributes}, valid_session
        }.to change(PersonalPlant, :count).by(1)
      end

      it "assigns a newly created personal_plant as @personal_plant" do
        post :create, {:personal_plant => valid_attributes}, valid_session
        assigns(:personal_plant).should be_a(PersonalPlant)
        assigns(:personal_plant).should be_persisted
      end

      it "redirects to the created personal_plant" do
        post :create, {:personal_plant => valid_attributes}, valid_session
        response.should redirect_to(PersonalPlant.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved personal_plant as @personal_plant" do
        # Trigger the behavior that occurs when invalid params are submitted
        PersonalPlant.any_instance.stub(:save).and_return(false)
        post :create, {:personal_plant => {}}, valid_session
        assigns(:personal_plant).should be_a_new(PersonalPlant)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PersonalPlant.any_instance.stub(:save).and_return(false)
        post :create, {:personal_plant => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested personal_plant" do
        personal_plant = PersonalPlant.create! valid_attributes
        # Assuming there are no other personal_plants in the database, this
        # specifies that the PersonalPlant created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PersonalPlant.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => personal_plant.to_param, :personal_plant => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested personal_plant as @personal_plant" do
        personal_plant = PersonalPlant.create! valid_attributes
        put :update, {:id => personal_plant.to_param, :personal_plant => valid_attributes}, valid_session
        assigns(:personal_plant).should eq(personal_plant)
      end

      it "redirects to the personal_plant" do
        personal_plant = PersonalPlant.create! valid_attributes
        put :update, {:id => personal_plant.to_param, :personal_plant => valid_attributes}, valid_session
        response.should redirect_to(personal_plant)
      end
    end

    describe "with invalid params" do
      it "assigns the personal_plant as @personal_plant" do
        personal_plant = PersonalPlant.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PersonalPlant.any_instance.stub(:save).and_return(false)
        put :update, {:id => personal_plant.to_param, :personal_plant => {}}, valid_session
        assigns(:personal_plant).should eq(personal_plant)
      end

      it "re-renders the 'edit' template" do
        personal_plant = PersonalPlant.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PersonalPlant.any_instance.stub(:save).and_return(false)
        put :update, {:id => personal_plant.to_param, :personal_plant => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested personal_plant" do
      personal_plant = PersonalPlant.create! valid_attributes
      expect {
        delete :destroy, {:id => personal_plant.to_param}, valid_session
      }.to change(PersonalPlant, :count).by(-1)
    end

    it "redirects to the personal_plants list" do
      personal_plant = PersonalPlant.create! valid_attributes
      delete :destroy, {:id => personal_plant.to_param}, valid_session
      response.should redirect_to(personal_plants_url)
    end
  end

end
